version: '3.4'

services:
  tracsess:
    image: tracsess
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 443:443
